---

services:
  reverse-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # DISABLE_IPV6: 'true'
    volumes:
      - /var/container-volumes/proxy-manager/data:/data
      - /var/container-volumes/proxy-manager/letsencrypt:/etc/letsencrypt  
    networks:
      - my_network  # Add to the shared network 

networks:
  my_network: