---

services:
  app:  # Combine both front-end and back-end into a single service
    build: ../../  # This assumes your Dockerfile is in the root directory
    environment:
      TZ: America/New_York
      SERVER_PORT: 3003
      API_ROUTE: 'https://group-media-geiwtdvjg-joshs-projects-9174c388.vercel.app/'
      DB_CONNECT: 'mongodb+srv://joshgoold2:D94uw6y8!!@nodejs-1.t5hzt.mongodb.net/?retryWrites=true&w=majority&appName=nodejs-1'
      JWT_SECRET: 'VERYS3CRETk3y'
      
    ports:
      - "3500:3500"  # Expose the application port
      - "3003:3003"  # Expose the application port
    depends_on:
      - mongodb
    networks:
      - my_network  # Add to the shared network


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: joshgoold2  # Correct MongoDB environment variables
      MONGO_INITDB_ROOT_PASSWORD: D94uw6y8!!
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data even after restart
    networks:
      - my_network  # Add to the shared network

volumes:
  mongo-data:

networks:
  my_network: